### ISSUE TITLE
mycroft-msm: command not found

### ISSUE THREAD

**Issue by danielnbalasoiu** [MycroftAI/mycroft-dinkum#47]
**Describe the bug**

**To Reproduce**
1. Configure SSH access to mycroft
2. SSH into the box
3. Run `mycroft-msm`, or `mycroft-msm -h`
4. See error `-bash: mycroft-msm: command not found`

**Expected behavior**
`mycroft-msm` is installed and can be used to manage skills.

**Environment (please complete the following information):**
 - Device type: Mark II
 - OS: Ubuntu
 - Mycroft-core version: 2022-10-18 06:11
 - Mycroft version: 21.2.1

**Additional context**
According to [Mycroft Skills Manager](https://mycroft-ai.gitbook.io/docs/skill-development/mycroft-skills-manager), I should be able to manage Mycroft's skill with `mycroft-msm` but it seems mycroft-dinkum has deprecated it. 
If there another way to install custom skill (TuneIn Radio for example)?

Thank you!

**Comment by jmillerv** [comment]
Not a good solution to the bug, but I just got mine this week and found this piece of documentation. https://mycroft-ai.gitbook.io/mark-ii/differences-to-classic-core/porting-classic-core-skills

I've yet to successfully port a skill over though.

**Comment by pfefferle** [comment]
Skills seems to work different under dinkum and the missing cli commands are on purpose https://github.com/MycroftAI/hardware-mycroft-mark-II/issues/95#issuecomment-1289972130
